### ISSUE TITLE
Can we download multiple online labs at once via ishare2?

### ISSUE THREAD

**Issue by tlsalex** [pnetlabrepo/ishare2#5]
Hi team,

currently, I download lab by going to the online lab store, and click on the lab one by one , which is downloading lab one by one, can we use ishare2 to download all labs under specific link. e.g. https://user.pnetlab.com/store/labs/view?group=2&groupName=CCNP

thanks.

**Comment by sudoalx** [comment]
Hi
That feature is not yet available, but we'll discuss if we can implement that. That requires web scraping the page where the labs are hosted on and for that we'll have to make an additional tool which could be an ishare2 add-on.
