### ISSUE TITLE
Ishare2 gui issue

### ISSUE THREAD

**Issue by Myztic90** [pnetlabrepo/ishare2#6]
When upgrading ishare2 with ishare2 upgrade and upgrade gui or even ishare2 the Gui stops working, not reachable at port 5000 and it seems like the webserver is not starting.

Temporary workaround is to download older version of ishare2 1.7.4 from github and chmod +x ishare2 and run it with ./ishare2 gui start

**Comment by 12Tall** [comment]
I met the similar issue, and I just upgrade the python installation to v3.7, then install the the service as <https://github.com/ishare2-org/ishare2-web-gui> showed. the web gui works, but I still get console connection issues with qemu images.  :(

**Comment by sudoalx** [comment]
A new version of ishare2 gui is being developed, stay tuned
