### ISSUE TITLE
Seems the repo.pnetlab.com was failed

### ISSUE THREAD

**Issue by 12Tall** [pnetlabrepo/ishare2#8]
When I try to install ishare2 client by 
`curl -o /usr/sbin/ishare2 https://raw.githubusercontent.com/pnetlabrepo/ishare2/main/ishare2`  

then it just shows:  
```txt
...
Reading package lists... Done
E: Failed to fetch http://repo.pnetlab.com/./Packages  404  Not Found [IP: 14.225.16.78 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
 [-] Failed to update package lists.
/usr/sbin/ishare2: line 68: syntax error near unexpected token `('
/usr/sbin/ishare2: line 68: `    read -p " [+] (y/n): " -r'
```

it did work last month, is there any changes on `repo.pnetlab.com`? THX.

**Comment by sudoalx** [comment]
> When I try to install ishare2 client by 
> `curl -o /usr/sbin/ishare2 https://raw.githubusercontent.com/pnetlabrepo/ishare2/main/ishare2`  
> 
> then it just shows:  
> ```txt
> ...
> Reading package lists... Done
> E: Failed to fetch http://repo.pnetlab.com/./Packages  404  Not Found [IP: 14.225.16.78 80]
> E: Some index files failed to download. They have been ignored, or old ones used instead.
>  [-] Failed to update package lists.
> /usr/sbin/ishare2: line 68: syntax error near unexpected token `('
> /usr/sbin/ishare2: line 68: `    read -p " [+] (y/n): " -r'
> ```
> 
> it did work last month, is there any changes on `repo.pnetlab.com`? THX.

repo.pnetlab.com is not related to ishare2 we're separate projects, but you should check your APT should probably check your DNS as I see you're having problems connecting to the Internet

**Comment by LesenHuang** [comment]
U try it
`root@ubuntu18.04 # echo "185.199.110.133   raw.githubusercontent.com" >>  /etc/hosts`

**Comment by LesenHuang** [comment]
Your problem should be solved by opening a network proxy.
